apiVersion: apps/v1
kind: Deployment
metadata:
  name: ack-sagemaker-controller
  namespace: ack-system
spec:
  template:
    spec:
      containers:
        - name: controller
          env:
          - name: AWS_REGION
            valueFrom:
              configMapKeyRef:
                name: ack-sagemaker-controller-install-parameters
                key: ACK_AWS_REGION
