apiVersion: v1
kind: Service
metadata:
  name: notebook-controller-service
  namespace: kubeflow
  annotations:
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
    prometheus.io/scrape: "true"
spec:
  ports:
    - port: 443
      name: webhook
    - port: 8080
      name: metrics
      protocol: TCP
      targetPort: 8080
